# Generated by Django 5.1.6 on 2026-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['category'], name='product_category_idx'), models.Index(fields=['product_name'], name='product_name_idx')],
            },
        ),
    ]
